// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://disphvujazcpzvzsmecp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpc3BodnVqYXpjcHp2enNtZWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDkzOTksImV4cCI6MjA2NzU4NTM5OX0.bAT_a1usdFjmcnjeGS3lzBSbhznD-bPgO5Q73Ia-D9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});